neutron-org/neutron-integration-tests

package.json
src/helpers/cosmos.ts
src/testcases/interchain_kv_query.test.ts

Assigned task: [LSC-125](https://p2pvalidator.atlassian.net/browse/LSC-125)
Tests for KV interchain queries:
- balance query;
- delegations query;
- transfers query;
- TX query callback failure;
- KV query callback failure.
Depends on:
- https://github.com/neutron-org/neutron-contracts/pull/18

Feat: KV query tests

---

src/helpers/cosmos.ts
src/testcases/interchaintx.test.ts

**Tasks**: 
* https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-152
* https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-129
What tests are implemented:
* custom timeout when submitting ICA tx;
* tests for reregistering ICA after it was closed by timeout.
**Test with**: 
* https://github.com/neutron-org/neutron-contracts/pull/20 
* https://github.com/neutron-org/neutron/pull/43

feat: tests for timeout logic and reopening ICA channel

---

src/testcases/interchain_kv_query.test.ts
src/testcases/interchain_tx_query.test.ts

MERGE and test with:
https://github.com/neutron-org/neutron/pull/92
https://github.com/neutron-org/neutron-contracts/pull/60

feat: update transaction filter tests

---

setup/Makefile
src/helpers/env.ts

1. After starting containers, test code request versions of the binaries inside the containers so we can be sure we're running the version we expect to run
2. Makefile fixed to pass the flags to neutron-query-relayer builder container

printing versions of services after starting containers

---

setup/dockerbuilds/Dockerfile.gaia
setup/dockerbuilds/Dockerfile.hermes
setup/dockerbuilds/Dockerfile.neutron
setup/hermes/config.toml
setup/node/add-consumer-section.sh
setup/node/add-gentx.sh
setup/node/init.sh

Make integration tests work with latest version of neutron with CCV modules.
It should work with `main` version of `neutron`.

fix: NTRN-278. Fix integration tests to work with interchain security

---

src/helpers/env.ts
src/helpers/wait.ts
src/testcases/interchaintx.test.ts

Because of delay in the connection creation using query relayer it is required to change approach used to detect connection established event.

fix: NTRN-267. Interchaintx tests. Add counterparty chain connection to be established

---

src/helpers/cosmos.ts
src/testcases/simple.test.ts

This PR adds really basic test for changes made in [this fix of Neutron code](https://github.com/neutron-org/neutron/pull/98)
The aim is to check if there is no ability to pay fees in denom that is not registered in MinFees parameter of the chain.
Ideally, this PR should be checked in a way where this test is run with main (`neutron_audit_oak_19_09_2022_fixes` atm) branch of Neutron first to ensure it fails and with `fix/fees-check-bypass` after that to ensure it passes.

(NTRN-275) Feat: Testing denom checking in feerefunder

---

src/helpers/cosmos.ts
src/testcases/simple.test.ts

This PR adds simple test for the fix made in Neutron: https://github.com/neutron-org/neutron/pull/96
During the review please ensure test fails with Neutron from the main (`neutron_audit_oak_19_09_2022_fixes`) branch and passes with `fix/query-failures-limit` branch.

(NTRN-275) feat: failures query limitation test

---

setup/node/init.sh
src/helpers/cosmos.ts
src/testcases/treasury.test.ts

Treasury tokens are vested based on on-chain activity: burnt_tokens * a_multiplier. The multiplier is an linear function of the supply: while initially, one burnt tokens equals multiple NTRN tokens made liquid, the flow of new tokens into the Treasury progressively slows down until the tokens supply is exhausted and the tokenomy becomes deflationary.
Depends on:
* https://github.com/neutron-org/neutron-dao/pull/15
* https://github.com/neutron-org/neutron/pull/117

feat: Implement burn-based vesting for treasury. NTRN-308

---

src/testcases/simple.test.ts

This commit just tries to perform the same IBC transfer all over again until it succeeds. This is a dirty workaround until we develop better means of triggering failures for rainy day tests.
Tests run: https://github.com/neutron-org/neutron-tests/actions/runs/3925139457

fix: workaround failing IBC transfer

---

src/helpers/dao.ts
src/testcases/subdao.test.ts

this PR prettifies `subdao.test.ts` and adds to it an additional test that updates subDAO config using a proposal
**contracts:** https://github.com/neutron-org/neutron-dao/pull/29
**tests result:** https://github.com/neutron-org/neutron-tests/actions/runs/3925298149.

feat: add test for subDAO config update via proposal

---

README.md
src/helpers/cosmos.ts
src/helpers/env.ts
src/helpers/ica.ts
src/helpers/icq.ts
src/helpers/wait.ts
src/testcases/common_localcosmosnet.ts
src/testcases/governance.test.ts
src/testcases/interchain_kv_query.test.ts
src/testcases/interchain_tx_query.test.ts
src/testcases/interchain_tx_query_resubmit.test.ts
src/testcases/interchaintx.test.ts
src/testcases/simple.test.ts
src/testcases/subdao.test.ts
src/testcases/tokenomics.test.ts
src/testcases/treasury.test.ts

Previous behaviour used to be HTTP polling busy loop.
[[NTRN-288](https://p2pvalidator.atlassian.net/browse/NTRN-288)] [[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/3939510159)]
[NTRN-288]: https://p2pvalidator.atlassian.net/browse/NTRN-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: NTRN-288: use websocket to wait for new block

---

src/helpers/cosmos.ts
src/helpers/wait.ts
src/testcases/subdao.test.ts

**task:** https://p2pvalidator.atlassian.net/browse/NTRN-329
**relative Neutron DAO contracts PR:** https://github.com/neutron-org/neutron-dao/pull/34
This PR:
- adds a test case for subDAO `update_config` with an empty `name` value which is supposed to be failed;
- brings a better logging for failed `getWithAttempts`: it wasn't possible to determine where exactly the failure occurred because not the logging nor the trace showed the cause, only the test where it happened in. With a little logging improvement it will be much more handy to parse such errors because of the payload it will contain;
- a little typo fix for `queryContract`.
**tests run:** https://github.com/neutron-org/neutron-tests/actions/runs/3995651043

feat: test invalid config

---

src/testcases/subdao.test.ts

[TEST RUN](https://github.com/neutron-org/neutron-tests/actions/runs/4054199243/jobs/6975934929)
Currently we get the main dao address (a.k.a. “owner“) from the instantiate message. Idea of this task is to get it automatically from the subdao core (implement a query) and remove the owner field from the instantiate message.

NTRN-345 rm owner in timelock contract 

---

package.json
setup/dockerbuilds/Dockerfile.hermes
src/helpers/cosmos.ts
src/helpers/dao.ts
src/testcases/lockdrop.test.ts

**task:** https://p2pvalidator.atlassian.net/browse/NTRN-343
This PR doesn't contain "stubs with TODOs" for lockdrop vault as it is said in the task's **DoD**, but provides a foundation with instantiation and several query and exec helpers for the contract. Motivation: it's not efficient to forecast the test flow at this point, but it's quite useful for the future to have the contract instantiation flow and these helpers implemented.
**relative PRs:**
- https://github.com/neutron-org/neutron-dao/pull/35
**tests run:** https://github.com/neutron-org/neutron-tests/actions/runs/4231771709

feat: add lockdrop vault NTRN-343

---

setup/Makefile
setup/docker-compose.yml
setup/dockerbuilds/Dockerfile.hermes

This PR will upgrade hermes to latest version of master branch on original repo. After merging our own fork of the hermes relayer repo (https://github.com/neutron-org/hermes) will not be required.
[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/4477253723)

Update hermes to latest version

---

setup/dockerbuilds/Dockerfile.hermes

Currently to run the integration tests locally one has to build the hermes image which implies building the hermes from sources. It takes significant time (like, dozens of minutes) while hermes version doesn't change much and it's not necessary to build it from scratch since it's the test environment.
This PR is to replace the building process with binary download. The caveat is if we will need a specific commit we'd need to roll back it to building once again.

download hermes binary instead of building it

---

src/helpers/tge.ts
src/helpers/tokenfactory.ts
src/helpers/types.ts
src/testcases/parallel/tge.investors_vesting_vault.test.ts
src/testcases/parallel/tge.vesting_lp_vault.test.ts
src/testcases/parallel/tokenfactory.test.ts
src/testcases/run_in_band/tge.auction.test.ts

**task:** https://p2pvalidator.atlassian.net/browse/NTRN-483
**this PR:**
- configures the vesting contract used by the generator with a native astro token;
- adds a vesting account for the generator making rewards available for LP (lockdrop);
- adds tests for generator rewards distribution across the lockdrop participants;
- refines lockdrop rewards tests;
- moves usable common tokenfactory funcs from the tokenfactory test file to a shared helpers file.
- https://github.com/neutron-org/neutron-tge-contracts/pull/49

[NTRN-483] feat: proper vesting for generator

---

src/helpers/types.ts
src/testcases/parallel/simple.test.ts
src/testcases/run_in_band/interchaintx.test.ts

updated data format to meet new failed acks format

Feat: icatx refactor

---

setup/docker-compose.yml

This PR removes redundant replacement of contracts used in neutron node container.
- https://github.com/neutron-org/neutron/pull/328

chore: rm contracts replacement in docker compose

---

.tool-versions
package.json
src/testcases/parallel/overrule.test.ts
src/testcases/parallel/subdao.test.ts
yarn.lock

Backport of https://github.com/neutron-org/neutron-integration-tests/pull/198
Tests for https://github.com/neutron-org/neutron-dao/pull/83

Feat: save failed result backport #ntrn-80

---

src/testcases/parallel/governance.test.ts

in wasmd 0.42.0 it's possible to pin upto 50 codeids in one msg, we have to reduce the amount of contracts we try to pin in the test

feat: updated codepinids amount

---

src/testcases/run_in_band/interchaintx.test.ts

[TASK](https://hadronlabs.atlassian.net/browse/NTRN-223)
related prs:
https://github.com/neutron-org/neutron-dev-contracts/pull/43
https://github.com/neutron-org/neutron-sdk/pull/134

Remove usage of deprecated data field in Neutron SDK ICTX helper for SDK 0.47 chains & update SDK 0.45 helper to backw compat NTRN-223

---

src/testcases/parallel/overrule.test.ts
src/testcases/parallel/subdao.test.ts
src/testcases/run_in_band/tge.auction.test.ts

https://hadronlabs.atlassian.net/browse/NTRN-258
- adds an additional TGE participant that has only one lockup in atom pool. The user also participates in liquidity migration. Read the reasoning for the user in the next point
- expands the liquidity migration process to three steps:
- migration of `airdropAuctionLockdropVestingMigration` (atom + usdc)
- migration of `cmInstantiator` (atom + usdc, it's the last usdc pool participant, so the pool gets staked, but atom pool is not yet, and the user then withdraws atom position from not yet staked pool)
- migration of `airdropAtomAuctionLockdropMigration` (atom, it's the last atom pool participant, so the pool gets staked)
- introduces several little fixes and additional tests
- https://github.com/neutron-org/neutron-tge-contracts/pull/89

fix: PCL lockdrop LP early staking

---

package.json
src/testcases/parallel/governance.test.ts
src/testcases/run_in_band/slinky.test.ts
yarn.lock

We need to whitelist RecoverClient and IBCSoftwareUpgrade messages since old messages (UpdateClient and UpgradeProposal respectively) is [deprecated](https://github.com/cosmos/ibc-go/releases/tag/v8.0.0) in ibc-go v8.0+.
Related PRs:
* https://github.com/neutron-org/neutron/pull/525
* https://github.com/neutron-org/neutronjsplus/pull/37

Feat: whitelist ibc proposal messages

---

package.json
yarn.lock

- bumps neutronjsplus version to the one that has increased gas limit for tokenfactory's MsgMint
- https://github.com/neutron-org/neutron/pull/581

chore: bump neutronjsplus to comply with tf v4

---

src/testcases/run_in_band/chain_manager.test.ts

https://hadronlabs.atlassian.net/browse/NTRN-400
- adds tests for both `MsgSoftwareUpgrade` and `MsgCancelSoftwareUpgrade` adminmodule messages being sent via respestive introduced chain manager strategies;
- refactors the cron `MsgAddSchedule` and `MsgRemoveSchedule` tests so they don't have SubDAO involved but an ordinary account. Decided to do that when handled accidentally failing `add schedule` test with a totally uninformative and untraceable error `expected executed, got execution_failed` on `AddSchedule` SubDAO proposal execution to 1) get rid of poor error; 2) speed the tests up (interaction with chain manager from an ordinary account is much faster than from the SubDAO). Viewing and understanding the cron-related diff will be much easier if you first check out the way the …

Feat: software upgrade via chain manager [NTRN-400]

---

package.json
src/testcases/run_in_band/chain_manager.test.ts
yarn.lock

Returned a type that is correctly JSON-serializable for contracts.
related pr: https://github.com/neutron-org/neutronjsplus/pull/74

fix: fixed ccv chain manager test
