neutron-org/neutron-integration-tests

.github/workflows/tests.yml
=> feat: lint gh workflow

package.json, src/helpers/cosmos.ts, src/helpers/env.ts, src/helpers/icq.ts, src/helpers/sleep.ts, src/helpers/wait.ts, src/testcases/interchain_kv_query.test.ts, src/testcases/interchain_tx_query.test.ts, src/testcases/interchaintx.test.ts, src/testcases/simple.test.ts, yarn.lock
Tracking task: [NTRN-171](https://p2pvalidator.atlassian.net/browse/NTRN-171).
=> Fix: exterminate race conditions

src/helpers/cosmos.ts, src/testcases/interchaintx.test.ts, src/testcases/simple.test.ts
This PR should be merged together with https://github.com/neutron-org/neutron/pull/83 and https://github.com/neutron-org/neutron-contracts/pull/56
=> Ibc-fees integration tests

src/helpers/cosmos.ts, src/testcases/simple.test.ts
**MERGE WITH:**
* https://github.com/neutron-org/neutron/pull/89
=> Feat: test IBC transfers from usual accounts

setup/Makefile
https://docs.docker.com/build/building/drivers/docker-container/#loading-to-local-image-store
=> fix: save newly built images into the local image store

README.md, src/helpers/cosmos.ts, src/testcases/interchaintx.test.ts, src/testcases/simple.test.ts
In this PR tests solution for the issue https://github.com/neutron-org/neutron/pull/84 from the audit report will be added.
More info: https://p2pvalidator.atlassian.net/browse/NTRN-253
=> feat: ignore sudo error on ACK

src/helpers/cosmos.ts, src/testcases/simple.test.ts
**MERGE WITH:**
* https://github.com/neutron-org/neutron/pull/90
=> Feat: test IBC transfers query

README.md, package.json, setup/docker-compose.yml, src/config.json, src/helpers/cosmos.ts, src/helpers/env.ts, src/helpers/icq.ts, src/testcases/common_localcosmosnet.ts, src/testcases/interchain_kv_query.test.ts, src/testcases/interchain_tx_query.test.ts, src/testcases/interchain_tx_query_resubmit.test.ts
test case for "resubmit failed tx" functionality
https://github.com/neutron-org/neutron-query-relayer/pull/65
contracts from pr https://github.com/neutron-org/neutron-contracts/pull/68 are required
=> feat: NTRN-260 resubmit failed txs test

package.json, src/helpers/cosmos.ts, src/testcases/treasury.test.ts
make sure you have artifacts from https://github.com/neutron-org/neutron-dao/pull/9
https://p2pvalidator.atlassian.net/browse/NTRN-286
=> feat: treasury/distribution tests #NTRN-286

src/helpers/cosmos.ts
=> feat: predict contract address

download_artifacts.js
This PR is to fix the function that checks if contracts are already downloaded. It had missed parameter and wrong logic
No tests are linked since the script isn't tested automatically anywhere. Please check it manually by double-downloading the binaries.
=> Small downloader script fix

src/generated/proto.cjs, src/generated/proto.d.ts, src/helpers/icq.ts, src/testcases/run_in_band/interchain_kv_query.test.ts
**task:** https://p2pvalidator.atlassian.net/browse/NTRN-352
**relative PRs:**
- https://github.com/neutron-org/neutron/pull/162
- https://github.com/neutron-org/neutron-sdk/pull/86
**tests run:** https://github.com/neutron-org/neutron-tests/actions/runs/4416009334
=> feat: add icq register ts NTRN-352

src/generated/proto.d.ts, src/testcases/run_in_band/interchain_kv_query.test.ts
**task:** https://p2pvalidator.atlassian.net/browse/NTRN-378
- update ICQ params proto;
- make params check more independent in KV query test.
**relative PRs:**
- https://github.com/neutron-org/neutron/pull/156
**tests:** https://github.com/neutron-org/neutron-tests/actions/runs/4392779384
=> feat: remove tx hashes in EndBlock NTRN-378

download_artifacts.js, src/testcases/run_in_band/subdao.test.ts
**task:** https://p2pvalidator.atlassian.net/browse/NTRN-402
- update voting registry init msg with mandatory owner field;
- add checksum comparison to `download_artifacts.js`.
**relative PRs:**
- https://github.com/neutron-org/neutron-dao/pull/43
- https://github.com/neutron-org/neutron/pull/166
**tests run:** https://github.com/neutron-org/neutron-tests/actions/runs/4446787903
=> fix: minor issues NTRN-402

package.json, src/helpers/cosmos.ts, src/helpers/types.ts, src/testcases/run_in_band/tge.airdrop.test.ts, src/testcases/run_in_band/tge.credits.test.ts, yarn.lock
[Task](https://p2pvalidator.atlassian.net/browse/NTRN-393)
[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/4431454198/jobs/7775001146)
=> NTRN-393 TGE airdrop tests 

package.json, src/generated/proto.cjs, src/generated/proto.d.ts, src/helpers/icq.ts
[TASK](LastSubmittedResultRemoteHeight: &height,)
[TEST](https://github.com/neutron-org/neutron-tests/actions/runs/4437847594/jobs/7805351863)
There are bunch of PRs:
1.  [Neutron node](https://github.com/neutron-org/neutron/pull/165)
2. [Query relayer](https://github.com/neutron-org/neutron-query-relayer/pull/76)
3. [Integration tests](https://github.com/neutron-org/neutron-integration-tests/pull/102)
4. [Dev contracts](https://github.com/neutron-org/neutron-dev-contracts/pull/10)
5. [SDK](https://github.com/neutron-org/neutron-sdk/pull/85)
=> NTRN-383 revision number and height in query

download_artifacts.js
Since we moved to the main branch as the default one everywhere we have to do it in the script as well.
Also made a couple of improvements in terms of message readability and refactored the code a bit.
=> Default branch change for script + minor messages improvements

src/testcases/run_in_band/tge.auction.test.ts
**task**: https://p2pvalidator.atlassian.net/browse/NTRN-423
- https://github.com/neutron-org/neutron-tge-contracts/pull/34
**Tests run:** https://github.com/neutron-org/neutron-tests/actions/runs/4661122561
=> add vesting extensions layer to exec msgs NTRN-423

src/testcases/run_in_band/tge.auction.test.ts, src/testcases/run_in_band/tge.credits.test.ts
Integration tests for:
- https://github.com/neutron-org/neutron-tge-contracts/pull/31
=> fix: audit #NTRN-436

README.md, src/testcases/run_in_band/interchaintx.test.ts
https://github.com/neutron-org/neutron-tests/actions/runs/4808145858
=> feat: adapt to gaia903

package.json, src/helpers/dao.ts, src/helpers/types.ts, src/testcases/parallel/lockdrop.test.ts, src/testcases/parallel/tge.investors_vesting_vault.test.ts, src/testcases/parallel/tge.vesting_lp_vault.test.ts
This pr:
- simplifies vaults (https://github.com/neutron-org/neutron-integration-tests/pull/142)
- adds investors vesting vault tests
Merge with:
- https://github.com/neutron-org/neutron-dao/pull/54
- https://github.com/neutron-org/neutron/pull/234
tested in https://github.com/neutron-org/neutron-tests/actions/runs/4869365486
=> feat: add investors vesting vault tests

src/helpers/dao.ts, src/helpers/types.ts, src/testcases/parallel/subdao.test.ts
[Related PR](https://github.com/neutron-org/neutron-dao/pull/67)
[Task](https://p2pvalidator.atlassian.net/browse/NTRN-454)
=> NTRN-442 subdao pre-propose without timelock

src/testcases/run_in_band/interchaintx.test.ts
**task:** https://p2pvalidator.atlassian.net/browse/NTRN-561
- https://github.com/neutron-org/neutron-dev-contracts/pull/20
=> [NTRN-561] add contract's state immutability test on sudo failures

package.json, src/helpers/cosmos.ts, src/helpers/dao.ts, src/helpers/types.ts, src/testcases/run_in_band/globalfee.test.ts
Test for the globalfees module on the Netron.
https://hadronlabs.atlassian.net/browse/NTRN-29
Related PRs:
https://github.com/neutron-org/neutron/pull/264
https://github.com/neutron-org/neutron-docs/pull/91
=> Feat: NTRN-29. Add global fee module

src/testcases/parallel/stargate_queries.test.ts
test that not allowlisted query does not work
=> add failing stargate test

.tool-versions, package.json, setup/hermes/config.toml, src/helpers/cosmos.ts, src/helpers/types.ts, src/testcases/parallel/governance.test.ts, src/testcases/parallel/overrule.test.ts, src/testcases/parallel/stargate_queries.test.ts, src/testcases/parallel/tge.vesting_lp_vault.test.ts, src/testcases/run_in_band/globalfee.test.ts
https://hadronlabs.atlassian.net/browse/NTRN-67
=> feat: update tests to sdk47 for globalfee #ntrn-67

src/testcases/parallel/governance.test.ts, src/testcases/run_in_band/interchaintx.test.ts, src/testcases/run_in_band/tge.auction.test.ts
**summary:**
Investors vault added in [this PR](https://github.com/neutron-org/neutron/pull/315) have mutated voting power expected at the governance and auction tests. Changes made to this PR adapt the tests to new voting power.
- https://github.com/neutron-org/neutron/pull/317
=> chore: increase bond amount for gov test dao members

src/testcases/parallel/tge.investors_vesting_vault.test.ts
**task:** https://hadronlabs.atlassian.net/browse/NTRN-106
**This PR:**
- extends investors vesting vault tests with historical voting power checks after vesting schedules addition/removal
=> [NTRN-106] feat: improve investors vesting vault historical VP tests

package.json, src/testcases/parallel/governance.test.ts, src/testcases/parallel/voting_registry.test.ts
**task:** https://hadronlabs.atlassian.net/browse/NTRN-78
This PR adds a dedicated test file for the new version of the voting registry contract introduced [here](https://github.com/neutron-org/neutron-dao/pull/75)
=> [NTRN-78] Feat: add voting registry tests

src/testcases/parallel/tge.investors_vesting_vault.test.ts, src/testcases/parallel/tge.vesting_lp_vault.test.ts
**task:** https://hadronlabs.atlassian.net/browse/NTRN-105
- https://github.com/neutron-org/neutron-tge-contracts/pull/59
=> [NTRN-105] feat: add vesting token immutability once set tests

gen-proto-pob.sh, src/generated/pob/proto.cjs, src/generated/pob/proto.d.ts, src/generated/pob/proto.js, src/helpers/cosmos.ts
regenerated types to make migration pob -> block-sdk
related PR: https://github.com/neutron-org/neutron/pull/324
=> chore: replaced pob with block-sdk

src/testcases/parallel/xyk_to_cl_migration.test.ts
- [TASK](https://hadronlabs.atlassian.net/jira/software/projects/NTRN/boards/3?selectedIssue=NTRN-144)
- [TEST RUN](https://github.com/neutron-org/neutron-tests/actions/runs/6663945274/job/18120028257)
- [DAO PR](https://github.com/neutron-org/neutron-dao/pull/97)
=> Move LP tokens owned by Reserve contract to Neutron Main DAO Core contract during liquidity migration NTRN-144

package.json, setup/hermes/create-conn.sh, src/testcases/parallel/governance.test.ts, yarn.lock
**this PR:**
Clarifies the error expected from the update client proposal execution:
was:
failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: failed to submit admin proposal legacy: failed to submit proposal: failed to submit proposal legacy: client: **no handler exists for proposal type**
now:
failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: failed to submit admin proposal legacy: failed to submit proposal: failed to submit proposal legacy: failed to execute proposal proposal struct: **cannot update Active subject client: invalid update client proposal**
- https://github.com/neutron-org/neutron/pull/408
- https://github.com/neutron-org/neutronjsplus/pull/15
=> fix: update client handler route

setup/hermes/config.toml
Relevant PR: https://github.com/neutron-org/neutron/pull/414
=> Fix: decrease trusting period for neutron

README.md, src/helpers/gaia.ts, src/testcases/run_in_band/interchain_kv_query.test.ts
Add support for the signing info queries.
Depends on:
- https://github.com/neutron-org/neutron-dev-contracts/pull/38
- https://github.com/neutron-org/neutron-sdk/pull/122
- https://github.com/neutron-org/neutronjsplus/pull/19
[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/7801343130)
=> feat: LIDO-68. Signing info query

src/helpers/gaia.ts, src/testcases/run_in_band/interchain_kv_query.test.ts
Test proposals votes KV queries
Relates on https://github.com/neutron-org/neutron-dev-contracts/pull/40
[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/8597409604)
=> Add proposal votes tests

package.json, yarn.lock
Test run: https://github.com/neutron-org/neutron-tests/actions/runs/8524920768
=> feat: updated neutronjsplus #NTRN-174

package.json, src/testcases/run_in_band/dex_stargate.test.ts, yarn.lock
Related PR: https://github.com/neutron-org/neutron/pull/401
=> Fix: pool metadata proto

src/testcases/run_in_band/dex_bindings.test.ts, src/testcases/run_in_band/dex_stargate.test.ts
Update dex deposit error strings for https://github.com/neutron-org/neutron/pull/541
=> Audit validate fix

src/testcases/run_in_band/interchain_kv_query.test.ts
https://hadronlabs.atlassian.net/browse/NTRN-235
- adds a test case for balances ICQ with multiple balances one of which is empty for the queried account
- https://github.com/neutron-org/neutron-dev-contracts/pull/41
- https://github.com/neutron-org/neutron-sdk/pull/130
=> [NTRN-235] Feat/improve balances query

package.json, src/testcases/run_in_band/feemarket.test.ts, src/testcases/run_in_band/globalfee.test.ts, yarn.lock
This reverts commit 82df9509351ea040a8a118d64126b2ec4224d807.
Related PR:
* https://github.com/neutron-org/neutron/pull/557
=> Feat: return globalfee tests

package.json
This reverts commit daa204250e739f21d4f5d9869ecc9991308880b3.
=> Revert "disable dex tests"

src/testcases/run_in_band/dex_grpc.test.ts
See https://github.com/neutron-org/neutron/pull/711
=> FEAT: Allow cancel inactive limit orders

src/testcases/run_in_band/dex_bindings.test.ts
Fix expected error for missing limit orders
=> fix dex bindings LO tests

src/testcases/run_in_band/dex_grpc.test.ts
see https://github.com/neutron-org/neutron/pull/938
=> Feat: fractional banking
